Milestone1
Arinpe/Calculator_-React pull request #1
Opened 2021-08-21 16:25 UTC by Arinpe

In this milestone is the first step to creating the calculator app as seen in the Microver-Odin project

2021-08-23 14:08 UTC, bellom requested changes
## Hi @Arinpe  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1. Kindly check my comments under this review;**

**2 README file doesn't appear on the file changes, so I'm forced to drop the comment here: kindly update your README file with the correct information, seems like you have Weather app setup, kindly use the normal setup for react app i.e `npm i` then `npm start`, and also add the correct live demo link**
![image](https://user-images.githubusercontent.com/31897434/130461661-aa3a4502-8c67-44ab-a49d-cb9bf7d85ad5.png)



**3. Kindly update your PR description, example below**
![image](https://user-images.githubusercontent.com/31897434/130461437-3b196fda-c95d-4041-afc6-83b65ece47e5.png)
 

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-08-23 14:08 UTC, bellom commented on milestone1/src/App.css
> +.App {
We don't need to create a new directory, `src/App` is ok.

And also let's delete unnecessary files and logos.

![image](https://user-images.githubusercontent.com/31897434/130460817-1f614d07-be95-4174-bfd1-0846385e1bb7.png)

2021-08-23 20:47 UTC, bellom commented
@Arinpe I can see your effort trying to fix the linter.

Please update your README with the correct information as I said above so we can get this PR approved, you won't need to send in another CRR.

2021-08-23 21:05 UTC, Arinpe commented
> @Arinpe I can see your effort trying to fix the linter.
> 
> Please update your README with the correct information as I said above so we can get this PR approved, you won't need to send in another CRR.
> And also update your live demo link with the correct link, the current one seems not working.
> 
> I will be on this PR for few mins.

I don't quite understand what you want me to do with the read me file because everything seems fine to me

2021-08-23 21:07 UTC, bellom commented
> > @Arinpe I can see your effort trying to fix the linter.
> > Please update your README with the correct information as I said above so we can get this PR approved, you won't need to send in another CRR.
> > And also update your live demo link with the correct link, the current one seems not working.
> > I will be on this PR for few mins.
> 
> I don't quite understand what you want me to do with the read me file because everything seems fine to me

![image](https://user-images👆 busercontent.com/31897434/130519393-d7e7d941-08d7-4ab9-80ab-ef751000e380.png)


👆 perhaps screenshot would help.

and also kindly confirm your live demo link and share it with me here.

2021-08-23 21:22 UTC, Arinpe commented
I am done with the requested changes

2021-08-23 21:27 UTC, bellom approved these changes
## Hi @Arinpe  :clap: 

To Improve:

README file:
React set up example:
```
- git clone `your repo`
- cd into the folder
- git checkout `branch-name`
- run `npm i`
- run `npm start`
```

# Status: Approved

**Best**

2021-08-24 09:03 UTC, merged

2021-08-24 09:04 UTC, bellom commented
## Hi @Arinpe  👏  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

CR can't review a merge PR, kindly create a new one.