Mileston 4
Arinpe/Calculator_-React pull request #5
Opened 2021-08-26 07:44 UTC by Arinpe

This is a continuation of the react calculator project as given by Microverse.

2021-08-26 19:32 UTC, whiz25 requested changes
## changes required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this milestone. You have come a long way. Well done!
### changes 🔕 🔕 🔕 
- you have a grammatical error in your repo description: `The app is capable is simple...`. Change that to: `The app is capable in simple...`
- check comments for more changes to make.


### Martin Afani
#### Slack: whiz25

2021-08-26 20:07 UTC, Arinpe commented
I don't quite understand the changes you want me to make

2021-08-26 20:43 UTC, addod19 requested changes
### Hi @Arinpe, 

Great work on reaching out about the changes requested by a previous reviewer 👏 
I have added a few comments that need your kind attention :smile: Sorry for the misunderstanding

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

__Happy coding__ :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-08-26 20:43 UTC, addod19 commented on src/components/App.js
>  import React from 'react';
### [Optional] but Important!!!
- I am unable to run the app successfully, hence could render the project invalid. But since this is not the first review I would ask you to solve the problem. **HINT** `Install react-router-dom` . **FILE** `nvbar.js`, also it would be better to correctly spell the navbar

2021-08-26 20:43 UTC, addod19 commented on src/components/App.js
> +    /* eslint-disable */
- Kindly avoid disabling ESLint rules, instead find a way to solve it and by so doing we write clean and readable code

2021-08-26 20:43 UTC, addod19 commented on src/components/nvbar.js
> +function Navbar() {
### Optional
- It would be better if we use ES6 arrow syntax instead of the "function" keyword" since we are using most of the ES6 syntax, it would be nice to keep the consistency

2021-08-26 20:43 UTC, addod19 commented on README.md
### [Optional] but very important
- It would be better if we use the recommended linter files used by all the students of [Microverse -> .github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml), also let us keep in mind not to change any of the linter files either directly or indirectly. **HINT**: `.eslinrc.json file`

2021-08-26 20:43 UTC, addod19 commented on src/components/App.js
>  import Display from './Display';
- It would be better if we improve our PR, PR is a way of summarising what we did in a particular project. Let us look at our project description and am sure we will find some summary of the project

2021-08-27 04:21 UTC, whiz25 commented
> I don't quite understand the changes you want me to make

Hey @Arinpe my apologies for not including the comments for suggestions. I must have forgotten. Please work on the changes suggested by my colleagues.

2021-08-28 12:43 UTC, whiz25 approved these changes
## approved 👍🏿👍🏿👍🏿
Nice work making the requested changes.
`react-router-dom` added to `package.json` and ES6 syntax used. 
Merge and proceed to the next milestone.


### Martin Afani
#### Slack: whiz25

2021-09-09 09:39 UTC, merged